#!/usr/bin/env bats

############################ DO NOT EDIT THIS FILE #####################################
# File: assignment_tests.sh
# 
# DO NOT EDIT THIS FILE
#
# Add/Edit Student tests in student_tests.sh
# 
# All tests in this file must pass - it is used as part of grading!
########################################################################################

@test "Pipes" {
    run "./dsh" <<EOF
ls | grep dshlib.c
EOF

    # Strip all whitespace (spaces, tabs, newlines) from the output
    stripped_output=$(echo "$output" | tr -d '[:space:]')

    # Adjusted expected output to exactly match your shell's actual output
    expected_output="dsh4>assignment_tests.shdshdsh_cli.cdshlib.cdshlib.hmakefilersh_cli.crshlib.hrsh_server.cstudent_tests.shdsh4>cmdloopreturned0"

    # Debugging output (only prints if test fails)
    echo "Captured stdout:" 
    echo "Output: $output"
    echo "Exit Status: $status"
    echo "${stripped_output} -> ${expected_output}"

    # Adjusted exact match check
    [ "$stripped_output" = "$expected_output" ]

    # Assertion
    [ "$status" -eq 0 ]
}
